// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqpvy53ZpNSe8m6FtXJj25GsTtggFHCQg',
    appId: '1:1066828047560:web:f4c5a742d02727037db1fd',
    messagingSenderId: '1066828047560',
    projectId: 'hyrdovision-app',
    authDomain: 'hyrdovision-app.firebaseapp.com',
    storageBucket: 'hyrdovision-app.firebasestorage.app',
    measurementId: 'G-ZKB7WZYRX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyButaqThsZISIhojpWzO5lbwmXrzaZ0YFU',
    appId: '1:1066828047560:android:441c415e6b26fe677db1fd',
    messagingSenderId: '1066828047560',
    projectId: 'hyrdovision-app',
    storageBucket: 'hyrdovision-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYXmGSmuTXWACImq3z8o7BqqG0FWkoRJ4',
    appId: '1:1066828047560:ios:86049619756c62957db1fd',
    messagingSenderId: '1066828047560',
    projectId: 'hyrdovision-app',
    storageBucket: 'hyrdovision-app.firebasestorage.app',
    iosBundleId: 'com.example.hydrovisionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYXmGSmuTXWACImq3z8o7BqqG0FWkoRJ4',
    appId: '1:1066828047560:ios:86049619756c62957db1fd',
    messagingSenderId: '1066828047560',
    projectId: 'hyrdovision-app',
    storageBucket: 'hyrdovision-app.firebasestorage.app',
    iosBundleId: 'com.example.hydrovisionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqpvy53ZpNSe8m6FtXJj25GsTtggFHCQg',
    appId: '1:1066828047560:web:55c8434bb50976ab7db1fd',
    messagingSenderId: '1066828047560',
    projectId: 'hyrdovision-app',
    authDomain: 'hyrdovision-app.firebaseapp.com',
    storageBucket: 'hyrdovision-app.firebasestorage.app',
    measurementId: 'G-M4Y2WBP855',
  );
}
